name: Go Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - Makefile
      - '.github/workflows/go-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - Makefile
      - '.github/workflows/go-tests.yml'

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache: true
          cache-dependency-path: go.sum

      - name: Run go test
        env:
          GOCACHE: ${{ runner.temp }}/gocache
        run: |
          mkdir -p "$GOCACHE"
          go test ./...
